/* 「人的处境」v2：真事叙事版。
   每条讲一件有据可查的真实事情（史实或权威机构统计），
   句子短、无比喻、不模糊；数据均在文中注明来源机构。 */
module.exports = {
  1:{cn:'一九四七年初，三个人开始在纽约起草这份文件：主席埃莉诺·罗斯福，黎巴嫩的马利克，中国的张彭春。他们写第一句时先定下一个前提——人的尊严不靠任何人授予。第一条的第一句话，就从这个前提开始。',
     tw:'一九四七年初，三個人開始在紐約起草這份文件：主席埃莉諾·羅斯福，黎巴嫩的馬利克，中國的張彭春。他們寫第一句時先定下一個前提——人的尊嚴不靠任何人授予。第一條的第一句話，就從這個前提開始。',
     en:'In early 1947, three people began drafting this document in New York: Eleanor Roosevelt as chair, Charles Malik of Lebanon, and Peng-chun Chang of China. Before writing the first sentence they fixed one premise: no one grants a person dignity. The first sentence of Article 1 begins from there.'},
  2:{cn:'这份宣言通过的同一年，一九四八年，南非国民党上台，开始把种族隔离写进法律：住哪个区、上哪个学校、坐哪节车厢，都由肤色决定。第二条是把这些做法逐条否定的清单。',
     tw:'這份宣言通過的同一年，一九四八年，南非國民黨上台，開始把種族隔離寫進法律：住哪個區、上哪個學校、坐哪節車廂，都由膚色決定。第二條是把這些做法逐條否定的清單。',
     en:'The year this Declaration was adopted, 1948, South Africa\'s National Party came to power and began writing apartheid into law: which district you lived in, which school you attended, which carriage you rode, all decided by skin colour. Article 2 is a list that negates those rules one by one.'},
  3:{cn:'一九四五年到一九四六年，纽伦堡的法庭第一次用「危害人类罪」审判一个国家机器对生命的系统屠杀。判决里写下的不是「战争输了」，而是「人的生命不能任意剥夺」。第三条把这层意思变成了每个人的权利。',
     tw:'一九四五年到一九四六年，紐倫堡的法庭第一次用「危害人類罪」審判一個國家機器對生命的系統屠殺。判決裡寫下的不是「戰爭輸了」，而是「人的生命不能任意剝奪」。第三條把這層意思變成了每個人的權利。',
     en:'In 1945 and 1946, the tribunal at Nuremberg for the first time tried a state\'s systematic killing as a crime against humanity. What the judgment recorded was not "the war was lost" but "human life may not be taken at will." Article 3 turns that into a right belonging to every person.'},
  4:{cn:'据国际劳工组织与伙伴机构二零二二年的联合估计，今天全球仍有约五千万人活在「现代奴隶制」里：强迫劳动、抵债劳动、强迫婚姻。这一条写的不是过去，是现在。',
     tw:'據國際勞工組織與夥伴機構二零二二年的聯合估計，今天全球仍有約五千萬人活在「現代奴隸制」裡：強迫勞動、抵債勞動、強迫婚姻。這一條寫的不是過去，是現在。',
     en:'A joint estimate by the International Labour Organization and partners in 2022 put the number of people living in modern slavery today at about fifty million: forced labour, debt bondage, forced marriage. This article is written about the present, not the past.'},
  5:{cn:'一八五九年，瑞士商人亨利·杜南路过意大利的索尔费里诺战场，看见约四万名死伤者躺在战场上，没有人管。他放下生意救伤，后来有了红十字会和《日内瓦公约》：各国承诺，对不再参战的人，禁止酷刑和虐待。第五条是把这条承诺写给每一个人。',
     tw:'一八五九年，瑞士商人亨利·杜南路過意大利的索爾費里諾戰場，看見約四萬名死傷者躺在戰場上，沒有人管。他放下生意救傷，後來有了紅十字會和《日內瓦公約》：各國承諾，對不再參戰的人，禁止酷刑和虐待。第五條是把這條承諾寫給每一個人。',
     en:'In 1859, the Swiss businessman Henry Dunant passed the battlefield of Solferino in Italy and saw some forty thousand dead and wounded lying there with no one to care for them. He set his business aside to help. From that came the Red Cross and the Geneva Conventions, under which states promise that torture and ill-treatment are forbidden. Article 5 extends that promise to every person.'},
  6:{cn:'一九三五年，纳粹德国颁布《帝国公民法》，宣布犹太人不再是公民。人还在，法律上却「不存在」了：不能起诉，不能订合同，财产被没收。第六条就是回答这件事：每一个人，在任何地方，都必须被法律承认为人。',
     tw:'一九三五年，納粹德國頒佈《帝國公民法》，宣佈猶太人不再是公民。人還在，法律上卻「不存在」了：不能起訴，不能訂合同，財產被沒收。第六條就是回答這件事：每一個人，在任何地方，都必須被法律承認爲人。',
     en:'In 1935, Nazi Germany\'s Reich Citizenship Law declared that Jews were no longer citizens. The people remained, but in law they "did not exist": they could not sue, could not make contracts, their property was confiscated. Article 6 is the answer: every person, everywhere, must be recognised as a person before the law.'},
  7:{cn:'宣言通过时，美国不少州的学校还实行「隔离但平等」：黑人孩子和白人孩子分开上学。六年之后的一九五四年，最高法院才在布朗案中裁定这种隔离违宪。第七条要的是：法律本身不偏袒任何人。',
     tw:'宣言通過時，美國不少州的學校還實行「隔離但平等」：黑人孩子和白人孩子分開上學。六年之後的一九五四年，最高法院才在布朗案中裁定這種隔離違憲。第七條要的是：法律本身不偏袒任何人。',
     en:'When the Declaration was adopted, schools in several American states still practised "separate but equal": Black children and white children taught apart. Six years later, in 1954, the Supreme Court ruled in Brown v. Board of Education that such segregation was unconstitutional. What Article 7 demands is that the law itself favour no one.'},
  8:{cn:'一二一五年，英格兰《大宪章》第三十九条写明：自由人非经依法审判，不得被拘捕、监禁或剥夺财产。这份八百多年前的文件，第一次把「先走法律，再动人」写成了白纸黑字。第八条把同一个道理，变成每个人都能实际使用的一条路。',
     tw:'一二一五年，英格蘭《大憲章》第三十九條寫明：自由人非經依法審判，不得被拘捕、監禁或剝奪財產。這份八百多年前的文件，第一次把「先走法律，再動人」寫成了白紙黑字。第八條把同一個道理，變成每個人都能實際使用的一條路。',
     en:'In 1215, clause 39 of England\'s Magna Carta stated that no free man shall be arrested, imprisoned or deprived of his property except by lawful judgment. That document, more than eight hundred years old, was among the first to put in writing that the law comes before any man is touched. Article 8 turns the same principle into a path every person can actually use.'},
  9:{cn:'一九三三年以后，纳粹德国用「保护性拘留」这个词，不经审判就把人无限期关进集中营：没有罪名，没有期限，没有律师。第九条禁止的，正是这种「带走一个人，不需要任何理由」。',
     tw:'一九三三年以後，納粹德國用「保護性拘留」這個詞，不經審判就把人無限期關進集中營：沒有罪名，沒有期限，沒有律師。第九條禁止的，正是這種「帶走一個人，不需要任何理由」。',
     en:'After 1933, Nazi Germany used the term "protective custody" to hold people in concentration camps indefinitely without trial: no charge, no time limit, no lawyer. What Article 9 forbids is exactly this: taking a person away without needing any reason.'},
  10:{cn:'一九四五年十一月到一九四六年十月，纽伦堡审判当着全世界记者的面公开进行：二十四名主要战犯被起诉，其中二十二人出庭受审，判决书用四种语言印发。第十条说，审判必须公开、法庭必须独立——因为秘密审判往往先有结论，再补「证据」。',
      tw:'一九四五年十一月到一九四六年十月，紐倫堡審判當著全世界記者的面公開進行：二十四名主要戰犯被起訴，其中二十二人出庭受審，判決書用四種語言印發。第十條說，審判必須公開、法庭必須獨立——因為秘密審判往往先有結論，再補「證據」。',
      en:'From November 1945 to October 1946, the Nuremberg trial was conducted openly before the world\'s press: twenty-four major war criminals indicted, twenty-two of them tried in court, the judgment published in four languages. Article 10 says trials must be public and courts independent, because secret trials usually reach the verdict first and find the "evidence" afterwards.'},
  11:{cn:'一七八九年，法国《人权与公民权宣言》第九条已经写明：任何人在被宣告有罪之前，都应被推定为无罪。一百五十九年后，这个道理进了世界宣言的第十一条，还加了一句：不能用事后制定的法律给人定罪。',
      tw:'一七八九年，法國《人權與公民權宣言》第九條已經寫明：任何人在被宣告有罪之前，都應被推定為無罪。一百五十九年後，這個道理進了世界宣言的第十一條，還加了一句：不能用事後制定的法律給人定罪。',
      en:'In 1789, article 9 of the French Declaration of the Rights of Man and of the Citizen already stated that every person is presumed innocent until declared guilty. A hundred and fifty-nine years later the same principle entered Article 11 of this Declaration, with one addition: no one may be convicted under a law made after the act.'},
  12:{cn:'一九四八年，乔治·奥威尔正在苏格兰的朱拉岛上写《一九八四》。他写的「老大哥在看着你」——墙上的屏幕、无时不在的监听——是一个隐私消失之后的世界。同一年，第十二条把住宅、家庭和通信划成国家不得任意进入的地方。',
      tw:'一九四八年，喬治·奧威爾正在蘇格蘭的朱拉島上寫《一九八四》。他寫的「老大哥在看著你」——牆上的屏幕、無時不在的監聽——是一個隱私消失之後的世界。同一年，第十二條把住宅、家庭和通信劃成國家不得任意進入的地方。',
      en:'In 1948, George Orwell was writing Nineteen Eighty-Four on the island of Jura in Scotland. His "Big Brother is watching you" — the screen on the wall, the listening that never stops — describes a world after privacy is gone. In that same year, Article 12 drew a line around home, family and correspondence, a place the state may not enter at will.'},
  13:{cn:'宣言通过前五个月，一九四八年六月，苏联封锁了通往西柏林的陆路。柏林变成一座孤岛，两百多万人靠空运生活了将近一年。第十三条写的「离开」和「返回」，在那一年不是抽象的词，是两百多万柏林人的现实。',
      tw:'宣言通過前五個月，一九四八年六月，蘇聯封鎖了通往西柏林的陸路。柏林變成一座孤島，兩百多萬人靠空運生活了將近一年。第十三條寫的「離開」和「返回」，在那一年不是抽象的詞，是兩百多萬柏林人的現實。',
      en:'Five months before this Declaration was adopted, in June 1948, the Soviet Union blockaded the land routes into West Berlin. The city became an island, its two million people supplied by air for almost a year. The "leave" and "return" written into Article 13 were not abstract words that year; they were the daily reality of more than two million people.'},
  14:{cn:'一九三九年，客轮「圣路易斯号」载着九百多名逃离德国的犹太难民横渡大西洋。古巴、美国、加拿大先后拒绝它靠岸，船只能开回欧洲，其中许多人后来死在集中营。第十四条写的「寻求和享受庇护」，就是给这样的船留一个可以靠岸的地方。',
      tw:'一九三九年，客輪「聖路易斯號」載著九百多名逃離德國的猶太難民橫渡大西洋。古巴、美國、加拿大先後拒絕它靠岸，船只能開回歐洲，其中許多人後來死在集中營。第十四條寫的「尋求和享受庇護」，就是給這樣的船留一個可以靠岸的地方。',
      en:'In 1939, the liner St. Louis crossed the Atlantic carrying more than nine hundred Jewish refugees fleeing Germany. Cuba, the United States and Canada in turn refused to let it land; the ship sailed back to Europe, and many of those aboard later died in the camps. The "seek and enjoy asylum" of Article 14 exists so that such a ship has somewhere to come ashore.'},
  15:{cn:'哲学家汉娜·阿伦特一九三七年被纳粹德国剥夺国籍，此后十四年没有任何国家的护照——她成了无国籍者。据联合国难民署统计，今天全球登记在册的无国籍者仍有四百多万，实际人数被认为远高于此，其中许多是孩子。第十五条说：国籍不是赏赐，不能随便拿走。',
      tw:'哲學家漢娜·阿倫特一九三七年被納粹德國剝奪國籍，此後十四年沒有任何國家的護照——她成了無國籍者。據聯合國難民署統計，今天全球登記在冊的無國籍者仍有四百多萬，實際人數被認為遠高於此，其中許多是孩子。第十五條說：國籍不是賞賜，不能隨便拿走。',
      en:'The philosopher Hannah Arendt was stripped of her German citizenship by the Nazis in 1937 and spent the next fourteen years without any country\'s passport: she was stateless. UNHCR still counts more than four million registered stateless people today, and the true figure is believed to be far higher — many of them children. Article 15 says nationality is not a favour, and it may not be taken away at will.'},
  16:{cn:'联合国儿童基金会估计，今天活着的妇女和女童里，约有六点四亿人在十八岁以前结过婚。她们中的许多人，在「我愿意」说出口之前没有任何选择。第十六条只要求一件事：结婚，必须两个人都自己愿意。',
      tw:'聯合國兒童基金會估計，今天活著的婦女和女童裡，約有六點四億人在十八歲以前結過婚。她們中的許多人，在「我願意」說出口之前沒有任何選擇。第十六條只要求一件事：結婚，必須兩個人都自己願意。',
      en:'UNICEF estimates that some 640 million women and girls alive today were married before the age of eighteen. Many of them had no choice at all before the words "I do" were said. Article 16 asks one thing only: marriage must be the free consent of the two people themselves.'},
  17:{cn:'在联合国的起草会议上，这一条吵得最凶：一派主张私有财产神圣不可侵犯，一派主张财产应当公有。最后的文字是双方都能接受的折中——承认财产权，同时禁止任意剥夺。第十七条是这场争论留下的产物。',
      tw:'在聯合國的起草會議上，這一條吵得最兇：一派主張私有財產神聖不可侵犯，一派主張財產應當公有。最後的文字是雙方都能接受的折中——承認財產權，同時禁止任意剝奪。第十七條是這場爭論留下的產物。',
      en:'No article was fought over harder in the United Nations drafting meetings: one side held private property sacred and inviolable; the other held that property belongs to all. The final text is the compromise both could accept: property rights recognised, arbitrary deprivation forbidden. Article 17 is what that argument left behind.'},
  18:{cn:'一五九八年，法王亨利四世签署《南特敕令》，让天主教徒和新教徒能在同一个国家各自信自己的。将近九十年后它被废除，但「信什么不能由命令决定」这个道理留了下来。第十八条把它写给了思想、良心和宗教。',
      tw:'一五九八年，法王亨利四世簽署《南特敕令》，讓天主教徒和新教徒能在同一個國家各自信自己的。將近九十年後它被廢除，但「信什麼不能由命令決定」這個道理留了下來。第十八條把它寫給了思想、良心和宗教。',
      en:'In 1598, King Henry IV of France signed the Edict of Nantes, allowing Catholics and Protestants to practise their own faith in the same country. It was revoked nearly ninety years later, but the principle survived: what a person believes cannot be decided by decree. Article 18 writes that principle for thought, conscience and religion.'},
  19:{cn:'两千五百多年前，郑国的子产没有拆毁国人议论朝政的「乡校」。他说：他们说得好，我就照做；他们反对的，我就改正——这是我的老师，为什么要拆？这大概是中国典籍里最早为公开议论辩护的记录。第十九条保护的，就是这种「能说」。',
      tw:'兩千五百多年前，鄭國的子產沒有拆毀國人議論朝政的「鄉校」。他說：他們說得好，我就照做；他們反對的，我就改正——這是我的老師，為什麼要拆？這大概是中國典籍裡最早為公開議論辯護的記錄。第十九條保護的，就是這種「能說」。',
      en:'More than twenty-five centuries ago, Zichan of Zheng refused to demolish the village school where people criticised the government. What they praise, I will do, he said; what they oppose, I will correct — they are my teachers, why tear it down? It may be the earliest defence of open criticism in the Chinese classics. Article 19 protects exactly that power to speak.'},
  20:{cn:'一九四八年七月，就在这份宣言通过前五个月，国际劳工组织通过了《结社自由和保护组织权公约》——工人组织工会的权利，第一次有了国际条约的明文。第二十条把同样的自由，写给了每一个人。',
      tw:'一九四八年七月，就在這份宣言通過前五個月，國際勞工組織通過了《結社自由和保護組織權公約》——工人組織工會的權利，第一次有了國際條約的明文。第二十條把同樣的自由，寫給了每一個人。',
      en:'In July 1948, five months before this Declaration was adopted, the International Labour Organization adopted the Freedom of Association and Protection of the Right to Organise Convention: for the first time, an international treaty expressly protected the right of workers to form unions. Article 20 writes the same freedom for every person.'},
  21:{cn:'宣言通过的那一年，瑞士的妇女还没有投票权，她们要等到一九七一年。起草国里也有这样的例子：智利到一九四九年才给妇女投票权，黎巴嫩要到一九五二年。第二十一条不是描述一九四八年的现实，是给世界定下标准。',
      tw:'宣言通過的那一年，瑞士的婦女還沒有投票權，她們要等到一九七一年。起草國裡也有這樣的例子：智利到一九四九年才給婦女投票權，黎巴嫩要到一九五二年。第二十一條不是描述一九四八年的現實，是給世界定下標準。',
      en:'In the year this Declaration was adopted, women in Switzerland still had no vote; they had to wait until 1971. Even among the drafting countries: Chile granted women the vote only in 1949, and Lebanon in 1952. Article 21 does not describe the reality of 1948; it sets the standard.'},
  22:{cn:'一九四二年，战时英国政府请经济学家贝弗里奇写了一份报告，主张国家应当托住失业、生病、衰老的人——「从摇篮到坟墓」的说法由此而来。六年后的第二十二条，把这份思路写成每个人的权利：社会应当接住撑不住的人。',
      tw:'一九四二年，戰時英國政府請經濟學家貝弗里奇寫了一份報告，主張國家應當托住失業、生病、衰老的人——「從搖籃到墳墓」的說法由此而來。六年後的第二十二條，把這份思路寫成每個人的權利：社會應當接住撐不住的人。',
      en:'In 1942, Britain\'s wartime government asked the economist William Beveridge to write a report proposing that the state should support the unemployed, the sick and the old — the origin of the phrase "from the cradle to the grave." Six years later, Article 22 made that idea the right of every person: society must catch those who can no longer hold on.'},
  23:{cn:'一九一九年，第一次世界大战后的和平会议创立了国际劳工组织，理由写进了《凡尔赛条约》：「普遍的持久和平，只能建立在社会正义的基础上。」一九五一年，它通过《同酬公约》（第 100 号）。第二十三条把这些写成每个人的权利。',
      tw:'一九一九年，第一次世界大戰後的和平會議創立了國際勞工組織，理由寫進了《凡爾賽條約》：「普遍的持久和平，只能建立在社會正義的基礎上。」一九五一年，它通過《同酬公約》（第 100 號）。第二十三條把這些寫成每個人的權利。',
      en:'In 1919, the peace conference after the First World War created the International Labour Organization, with the reason written into the Treaty of Versailles: universal and lasting peace can be established only if it is based upon social justice. In 1951 the ILO adopted the Equal Remuneration Convention (No. 100). Article 23 makes these things the right of every worker.'},
  24:{cn:'一八八六年五月，美国芝加哥的工人上街要求八小时工作制，罢工中发生爆炸，四名工人后来被判绞刑。为了纪念他们，才有了五一国际劳动节。第二十四条写的休息和带薪假期，就是从这一百多年的争取里来的。',
      tw:'一八八六年五月，美國芝加哥的工人上街要求八小時工作制，罷工中發生爆炸，四名工人後來被判絞刑。為了紀念他們，才有了五一國際勞動節。第二十四條寫的休息和帶薪假期，就是從這一百多年的爭取裡來的。',
      en:'In May 1886, workers in Chicago marched for the eight-hour day. A bomb exploded during the strike, and four workers were later hanged. May Day was created in their memory. The rest and paid holidays written into Article 24 came out of more than a century of such struggle.'},
  25:{cn:'世界卫生组织成立于一九四八年四月七日，与这份宣言同一年。它的章程开宗明义：健康不只是没有病，而是身体、心理和社会都完好的状态。第二十五条说的食物、衣着、住房和医疗，就是这种「完好」的底子。',
      tw:'世界衛生組織成立於一九四八年四月七日，與這份宣言同一年。它的章程開宗明義：健康不只是沒有病，而是身體、心理和社會都完好的狀態。第二十五條說的食物、衣著、住房和醫療，就是這種「完好」的底子。',
      en:'The World Health Organization was founded on 7 April 1948, the same year as this Declaration. Its Constitution opens with a definition: health is a state of complete physical, mental and social well-being, not merely the absence of disease. The food, clothing, housing and medical care named in Article 25 are the foundation of that well-being.'},
  26:{cn:'联合国教科文组织统计，今天全球仍有约七点七亿成年人不会读写，其中三分之二是妇女。也就是说，一九四八年写下的「人人都有受教育的权利」，到今天还没有全部兑现。第二十六条不是纪念碑，是待办清单。',
      tw:'聯合國教科文組織統計，今天全球仍有約七點七億成年人不會讀寫，其中三分之二是婦女。也就是說，一九四八年寫下的「人人都有受教育的權利」，到今天還沒有全部兌現。第二十六條不是紀念碑，是待辦清單。',
      en:'UNESCO counts about 770 million adults in the world today who cannot read or write, two thirds of them women. In other words, the "everyone has the right to education" written down in 1948 has still not been fully delivered. Article 26 is not a monument; it is a to-do list.'},
  27:{cn:'一八八六年，十多个国家在瑞士伯尔尼签署《伯尔尼公约》，第一次约定：作者的作品跨出国界，也受保护。这大概是「保护创作者」第一次成为国际约定。第二十七条更进一步：作者的精神利益，也要保护。',
      tw:'一八八六年，十多個國家在瑞士伯爾尼簽署《伯爾尼公約》，第一次約定：作者的作品跨出國界，也受保護。這大概是「保護創作者」第一次成為國際約定。第二十七條更進一步：作者的精神利益，也要保護。',
      en:'In 1886, more than ten countries signed the Berne Convention in Switzerland, agreeing for the first time that an author\'s work is protected when it crosses borders. It was perhaps the first time that protecting creators became an international agreement. Article 27 goes further: the author\'s moral interests are protected too.'},
  28:{cn:'一九四五年《联合国宪章》生效，世界第一次有了一个以「免后世再遭战祸」开头的组织。三年后，这份宣言成为它发布的第一份普遍性权利文件。第二十八条说：每一个人，都有权要求一个让这些权利真正兑现的世界。',
      tw:'一九四五年《聯合國憲章》生效，世界第一次有了一個以「免後世再遭戰禍」開頭的組織。三年後，這份宣言成為它發佈的第一份普遍性權利文件。第二十八條說：每一個人，都有權要求一個讓這些權利真正兌現的世界。',
      en:'The Charter of the United Nations took effect in 1945, creating the first world organization whose opening words speak of saving succeeding generations from the scourge of war. Three years later, this Declaration became its first universal bill of rights. Article 28 says every person may claim a world in which these rights actually come true.'},
  29:{cn:'在联合国的起草会议上，有人担心：如果一份文件只讲权利、不讲义务，会不会变成「想干什么就干什么」的许可证？最后的回答是第二十九条：权利可以受法律限制，但这个限制本身，只能是为了尊重别人的权利和自由。',
      tw:'在聯合國的起草會議上，有人擔心：如果一份文件只講權利、不講義務，會不會變成「想幹什麼就幹什麼」的許可證？最後的回答是第二十九條：權利可以受法律限制，但這個限制本身，只能是為了尊重別人的權利和自由。',
      en:'At the United Nations drafting meetings, some worried that a document speaking only of rights and never of duties might become a licence to do anything one likes. The answer became Article 29: rights may be limited by law, but the limitation itself may exist only to secure respect for the rights and freedoms of others.'},
  30:{cn:'联合国的起草者特意加了最后一条，为的是防止这份宣言被反过来用：有人打着「权利」的旗号，去破坏别人同样的权利。第三十条是这份文件给自己的保险——权利不能成为拆掉权利的锤子。',
      tw:'聯合國的起草者特意加了最後一條，為的是防止這份宣言被反過來用：有人打著「權利」的旗號，去破壞別人同樣的權利。第三十條是這份文件給自己的保險——權利不能成為拆掉權利的錘子。',
      en:'The United Nations drafters added this final article on purpose: to stop the Declaration from being turned against itself by someone who invokes "rights" in order to destroy the same rights of others. Article 30 is the document\'s insurance against itself: a right must never become the hammer that breaks rights.'}
};
